[
{
  "filters": [

  ],
  "id": "message",
  "order": 0,
  "predicates": [{
                   "args": {
                     "pattern": "/api/v1/message/**"
                   },
                   "name": "Path"
                 }],
  "uri": "lb://com.message"
},

{
  "filters": [

  ],
  "id": "hotel",
  "order": 0,
  "predicates": [{
                   "args": {
                     "pattern": "/api/v1/hotel/**"
                   },
                   "name": "Path"
                 }],
  "uri": "lb://com.hotel"
}

  ,
{
  "filters": [

  ],
  "id": "coupon",
  "order": 0,
  "predicates": [{
                   "args": {
                     "pattern": "/api/v1/coupon/**"
                   },
                   "name": "Path"
                 }],
  "uri": "lb://com.coupon"
}

]