server:
  port: 8080
  shutdown: graceful

logging:
  config: classpath:logback-spring.xml

spring:
  application:
    name: ai.prime.gateway
  main:
    allow-circular-references: true
    allow-bean-definition-overriding: true

knife4j:
  enable: true


management:
  endpoint:
    web:
      exposure:
        include: '*'